project_id = "idaily"

[auth]
site_url = "http://localhost:3000"
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false

[auth.hook.password_verification_attempt]
enabled = true
uri = "pg-functions://postgres/public/hook_password_verification_attempt"
