-- Required RBAC role/permission catalog is installed idempotently by
-- supabase/migrations/20261006113000_reporting_integrity_and_catalog.sql.
--
-- Keep this file intentionally free of application-required production data so
-- a clean database behaves the same whether or not a deployment runner executes
-- Supabase seed hooks. Test/user fixtures belong in the pgTAP/Auth test suites.
